<a href="https://colab.research.google.com/github/Dhiru-py/NLP/blob/master/One_hot_Encoding_using_Python%2C_Scikit_learn_and_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#======================== Onehot_encoding with Python ====================================#

In [42]:
# Onehot-Embedding for Characters 

# define input string
data = 'hello world'
print(data)

# define universe of possible input values
alphabet = 'abcdefghijklmnopqrstuvwxyz'

hello world


In [43]:
# define a mapping of chars to integers
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
print (char_to_int)
int_to_char = dict((i, c) for i, c in enumerate(alphabet))


{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [36]:
# integer encode input data
integer_encoded = [char_to_int[char] for char in data if char in char_to_int]
print(integer_encoded)


[7, 4, 11, 11, 14, 22, 14, 17, 11, 3]


In [44]:
# one hot encode
onehot_encoded = list()

for value in integer_encoded:
	letter = [0 for _ in range(len(alphabet))]
	letter[value] = 1
	onehot_encoded.append(letter)
print (onehot_encoded)


[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [45]:
# invert encoding
import numpy as np
from numpy import argmax
inverted = int_to_char[argmax(onehot_encoded[0])]
print(inverted)

h


In [77]:
# Onehot_encoding for words
# define input string
data = 'dhirendra is a good boy and good in sports too'

# define universe of possible input values
dataset = 'dhirendra is a good NLP scholar and in study too'

In [78]:
# define a mapping of words to integers

words_to_integer = dict( (word_int, word) for word, word_int in enumerate(dataset.split (" ")))
words_to_integer

{'NLP': 4,
 'a': 2,
 'and': 6,
 'dhirendra': 0,
 'good': 3,
 'in': 7,
 'is': 1,
 'scholar': 5,
 'study': 8,
 'too': 9}

In [79]:
data_encode = [ words_to_integer[word] for word in data.split(" ") if word in  words_to_integer]
data_encode

[0, 1, 2, 3, 6, 3, 7, 9]

In [84]:
# let's create One-hot encoding...
Onehot_encoder = list()

for value in data_encode:
  dimentions = [0 for word in words_to_integer]
  dimentions[value] =1
  Onehot_encoder.append(dimentions)
Onehot_encoder

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

In [85]:
#======================== Onehot_encoding with Scikit-learn ====================================#

In [86]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder


In [87]:
# define example
#data = ['dhirendra', 'is', 'a', 'good', 'NLP', 'scholar' ,'and', 'good', 'in', 'sports', 'too']
data = ['dhirendra', 'is', 'a', 'good', 'boy', 'and', 'good' ,'in', 'sports', 'too']
print (data)

['dhirendra', 'is', 'a', 'good', 'boy', 'and', 'good', 'in', 'sports', 'too']


In [88]:
# integer encode
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

#integer_encoded = label_encoder.fit_transform(values)
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)


[3 6 0 4 2 1 4 5 7 8]


In [89]:
# binary encode
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(sparse=False)

integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


[[0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [90]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[3, :])])
print(inverted)

['good']


In [91]:
#======================== Onehot_encoding with Keras ====================================#

In [92]:
from keras.utils.np_utils import to_categorical
from numpy import array

In [93]:
# define example
data = ['dhirendra', 'is', 'a', 'good', 'NLP', 'scholar' ,'and', 'good', 'in', 'sports', 'too']


In [94]:
data_to_int = dict( (word_int, word) for word, word_int in enumerate (data))

data_encode = [data_to_int[word] for word in data if word in data_to_int]
data_encode

[0, 1, 2, 7, 4, 5, 6, 7, 8, 9, 10]

In [95]:
# one hot encode
encoded = to_categorical(data_encode)
print(encoded)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [96]:
# invert encoding
inverted = argmax(encoded[3])
print(inverted)

7
